### ISSUE TITLE
azure/ug-secops-vnet/060-nva.tf relative path fails when used as a child module.

### ISSUE THREAD

**Issue by graememeyer** [StrangeBeeCorp/cloud-distrib-resources#1]
https://github.com/StrangeBeeCorp/cloud-distrib-resources/blob/0712a1463e1d93d22eea53fa8015fefd6394e75f/azure/ug-secops-vnet/060-nva.tf#L84

This line causes an issue if you're using these modules as child modules because the relative path is calculated from the root module, not the child module. 

e.g. to write the path explicitly if you're using it as a child module it would be something like:

```Terraform
    custom_data = file("modules/cloud-distrib-resources/azure/ug-secops-vnet/files/nva-nat-cloud-config.yaml")
```

It looks like you can use [`${path.module}`](https://www.terraform.io/docs/language/expressions/references.html#filesystem-and-workspace-info) to refer to the base dir of the module (as opposed to ${path.root} which refers to the root module directory). Swapping this in should allow this to work in both dedicated / root scenarios, as well as when using as a child module:

``` Terraform
    custom_data = file("${path.module}/files/nva-nat-cloud-config.yaml")
```

**Comment by AlexandreGohier** [comment]
Thank you for reporting this and sorry it took so long to get back to you. We have implemented the change in [1ee30c1](https://github.com/StrangeBeeCorp/cloud-distrib-resources/commit/1ee30c157a22d1b2d41f061c1a72123ae210fdd8) for all files that could have a relative path.
