### ISSUE TITLE
AWS | Error: Your query returned no results. Please change your search criteria and try again.

### ISSUE THREAD

**Issue by ezztahoun** [StrangeBeeCorp/cloud-distrib-resources#2]
Unable to find AMIs give the strangebee owner acc number and the names/prefixes. 

Setting the variable to full name or prefix or even ami ID doesnt fix this.

**Comment by ezztahoun** [comment]
`│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with data.aws_ami.secops_thehive_ami,
│   on main.tf line 51, in data "aws_ami" "secops_thehive_ami":
│   51: data "aws_ami" "secops_thehive_ami" {
│ 
╵
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with data.aws_ami.secops_cortex_ami,
│   on main.tf line 73, in data "aws_ami" "secops_cortex_ami":
│   73: data "aws_ami" "secops_cortex_ami" {`

**Comment by JoeWroe** [comment]
+1 to this issue, we are also experiencing it. Any help would be appreciated!

**Comment by JoeWroe** [comment]
The StrangeBee account number is different to the one pulled down with this repo. The `terraform plan/apply` will work if you update it in the `variables.tf` file. 

Steps to solve:

1. Find any `TheHive*` or `Cortex3*` image by searching 'Public Images' in the AMI's interface of the AWS console.
2. Click on the 'AMI id' of any image you're interested in.
3. Copy the 'Owner account ID'
4. Paste the ID into your copy of the `variables.tf` file. It was the 3rd terraform block for me, right at the top of the file under Global Config.

**Comment by AlexandreGohier** [comment]
Fixed in [bebd977](https://github.com/StrangeBeeCorp/cloud-distrib-resources/commit/bebd97750498d5f0adee379e96c91a3cbc6ada7b)
